from os.path import dirname as file_loc

from . import cmd_main

from.cmd_fragments._json import read_json

STR_FILE = str(file_loc(__file__))
STR_INV_FILE = STR_FILE + '/cmd_data/cmd_invite.json'

async def cmd_func(cmd_trigger, cmd_str, msg_obj, **kwargs):
    inv_data = read_json(STR_INV_FILE)

    cmd_args = cmd_str.split(" ")
    if len(cmd_args) < 2:
        invite_url = inv_data["invite_url"]
        resp_str = "".join([
            "The bot developer thanks you heartily for considering adding the bot to your guild.\n",
            "Please be aware that all information that isn't statistical is user-created content.\n",
            "This means that there is a massive possibility that you might get a result that you might not like.\n",
            "\nBy using this bot, you accept that:\n",
            " - Any video thumbnail/description/tag has been set by the\n",
            "video author on YouTube\n",
            " - Any playlist thumbnail/descriptin has been set by the\n",
            "playlist author on YouTube\n",
            " - Any content that isn't statistics generated by the bot\n",
            "is deemed explicitly the property of the content creator,\n",
            "unless they state otherwise\n",
            " - Any other references to information or data that isn't generated by the bot is property of Alphabet® Inc.\n\n"
            "Here is the invite link! [Invite to my guild]({0})".format(invite_url)
        ])
        out_embed = cmd_main.Embed(
            title = "Invite Request",
            description = resp_str,
            colour = 0x66FF66
        )
    elif len(cmd_args) >= 2:
        if cmd_args[1] == "guild":
            resp_str = "".join([
                "The bot owner welcomes you to visit the bot's guild. Please click the following link.\n",
                "[Join the guild]({0})".format(inv_data["invite_guild_url"])
            ])
        out_embed = cmd_main.Embed(
            title = "Invite Request Command",
            description = resp_str,
            colour = 0x66FF66
        )
    return {
        "output_msg": await msg_obj.channel.send(kwargs["msg_cmd_compiled"], embed = out_embed),
        "output_admin": False
    }

cmd_invite = cmd_main.Command(
    "invite",
    "invite inv i",
    {
        "global": {
            "output_syntax": "{0} <OPTIONAL guild>",
            "output_description": "Gives you either the invite URL for the bot, or\nthe invite URL to the bot's guild, depending on the request."
        },
        "guild": {
            "output_syntax": "{0}",
            "output_description": "Gives you the URL for the bot's support guild for you to join."
        }
    },
    "Gives you invite URLs for either the bot, or to the bot's support guild.",
    cmd_func,
    False
)